const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    name: "Green Sarry",
    price: 25,
    image: "https://assets0.mirraw.com/images/9196236/kalamkari_10_rama__%281%29_original_zoom.jpeg?1625150821",
    company: "Levis",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recEHmzvupvT8ZONH",
    name: "NAVY BLUE PRINTED SAREE",
    price: 60,
    image: "https://assets0.mirraw.com/images/6809576/image_zoom.jpeg?1551520082",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "rec5NBwZ5zCD9nfF0",
    name: "SILK SAREE",
    price: 50,
    image: "https://assets0.mirraw.com/images/8853996/IMG_4051_zoom.jpg?1616856499",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    amount: 1,
    stock: 4,
  },
  {
    id: "recd1jIVIEChmiwhe",
    name: "MAROON SILK SAREE",
    price: 70,
    image: "https://assets0.mirraw.com/images/7004479/PARI-38_MAROON_zoom.jpg?1557294370",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoM2MyHJGHLVi5l",
    name: " DARK GREEN SILK WITH SAREE",
    price: 80,
    image: "https://assets0.mirraw.com/images/7219772/7044R_zoom.jpg?1563789874",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recotY5Nh00DQFdkm",
    name: "Maroon Silk Sarry",
    price: 20,
    image: "https://assets0.mirraw.com/images/10665094/image_zoom.jpeg?1660498930",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "rec1Ntk7siEEW9ha1",
    name: "BLUE BANARASI-SAREES",
    price: 40,
    image: "https://assets0.mirraw.com/images/8896558/A_75_N_blue_1_zoom.jpg?1618395825",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "recNZ0koOqEmilmoz",
    name: "NAVY BLUE WOVEN BANARASI SAREE",
    price: 90,
    image: "https://assets0.mirraw.com/images/8547931/image_zoom.jpeg?1607934726",
    company: "Levis",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "recrfxv3EwpvJwvjq",
    name: "SILK BANDHANI SAREES SAREE",
    price: 100,
    image: "https://assets0.mirraw.com/images/8664323/Paryan-2429_zoom.jpg?1611401882",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoW8ecgjtKx2Sj2",
    name: "CHOCOLATE BROWN SARRY",
    price: 20,
    image: "https://assets0.mirraw.com/images/10224076/3605-1_zoom.jpg?1651236012",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    amount: 1,
    stock: 5,
  },
];
export default data;
